# x=input("Enter your first number : \n")
# y=input("Enter your second number : \n")
# z=int(x)+int(y)
# print(z)
# str1="kanhu"
# print(id(str1))
# str2="charan"
# print(id(str1))
shopping_list = ["milk", "bread", "poha", "curd"]
shopping_list.append("Biscuit")
print(shopping_list)
shopping_list.insert(1, "eggs")
shopping_list.insert(1, "fruit")
print(shopping_list)
shopping_list.extend(["chips", "salt"])
print(shopping_list)
shopping_list.pop()
print(shopping_list)
shopping_list.index("fruit")
print(shopping_list)
shopping_list.reverse()
print(shopping_list)
shopping_list.sort()
print(shopping_list)
shopping_list[0]="kanhu"
print(shopping_list)